apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  namespace: openvalue-ops
  name: slack-notify
spec:
  params:
    - name: text
      type: string
  steps:
    - name: notify
      image: "alpine:latest"
      script: |
        apk add curl
        curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"$(params.text)\"}" <URL_HERE>
