apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  namespace: openvalue-ops
  generateName: hello-world-service-run-
spec:
  pipelineRef:
    name: hello-world-service
  params:
    - name: commit
      value: e041be9627a74865694a1a327a8ec3f00ffe7e8f
    - name: branch
      value: openvalue-demo
  workspaces:
    - name: maven-settings
      emptyDir: {}
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: gcpcreds
      secret:
        secretName: gcp-creds
