apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  namespace: openvalue-ops
  generateName: hello-world-service-run-
spec:
  pipelineRef:
    name: hello-world-service
  params:
    - name: commit
      value: 0075e2b8900e7ed0fe595f36dba141536d476d5f
    - name: branch
      value: master
  workspaces:
    - name: maven-settings
      emptyDir: {}
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: gcpcreds
      secret:
        secretName: gcp-creds
